Update returns naming
msupply-foundation/msupply_docs pull request #90
Opened 2024-09-24 04:30 UTC by roxy-dao

returns naming

2024-09-24 22:32 UTC, CarlosNZ commented
> hopefully I have them the right way around

Yes, if only there was a way for the name itself to indicate which way round they go!  Oh wait.... 👀

2024-09-25 22:24 UTC, lache-melvin commented on content/docs/distribution/customer_returns.md
> +An Customer Returns is used to record stock which is returned by a customer.
Can we fix an -> a everywhere 🥺

2024-09-25 22:26 UTC, lache-melvin requested changes
Looks good! Just wanna fix all the `an`s hehe

2024-09-26 00:22 UTC, lache-melvin requested changes

2024-09-26 00:22 UTC, lache-melvin commented on content/docs/distribution/customer_returns.md
> +a Customer Returns is used to record stock which is returned by a customer.
Hehe ok nit one more time... sentences should start with capital 🙈

2024-09-26 00:22 UTC, lache-melvin commented on content/docs/distribution/customer_returns.md
> +It is important to be able to receive goods back from a customer without it being counted as goods coming from a supplier. If your customer issues the goods to you on an Outbound Shipment, and you th
here too

2024-09-26 00:22 UTC, lache-melvin commented on content/docs/replenishment/inbound_shipments.md
> +- the `OK` button. a Supplier Return will be created, and you will be redirected to view it. The quantities of stock selected to return will be reserved for the new return.
oop and here

2024-09-26 00:22 UTC, lache-melvin commented on content/docs/replenishment/supplier_returns.md
> +It is important to be able to return goods to a supplier without it being counted as goods being issued to a customer. If you just issue goods to your supplier through an Outbound Shipment, then thos
one more 😁

2024-09-26 00:28 UTC, lache-melvin approved these changes
third time's the charm 🎉

2024-09-26 00:29 UTC, merged